<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , chat-widget, , ))_chat-widget</name>
   <tag></tag>
   <elementGuidId>4f18ff0e-97a6-47f1-a8a3-f8502e540df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chat-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='chat-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>51368fae-42e6-4aa9-afb3-80aa389e1f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay; microphone *; camera *; display-capture *; picture-in-picture *; fullscreen *;</value>
      <webElementGuid>a17764e5-9dcf-4f9d-8ab8-008a487f14a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://secure.livechatinc.com/customer/action/open_chat?license_id=14037057&amp;group=3&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0</value>
      <webElementGuid>159e940c-0544-4329-b9b1-40cd804d58f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>18307e42-a413-444b-a387-3e85b67fb685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>d51a2d90-591b-4ddb-b41c-6b1b29188ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>a7d02eec-66e8-474f-aefe-2c7042d5369b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>LiveChat chat widget</value>
      <webElementGuid>c2a74dae-324c-4944-b494-2ee3231142fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d8a4dece-4944-4ae1-8983-b39305c6ec4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chat-widget&quot;)</value>
      <webElementGuid>c94942bf-e893-4b67-ab63-72c1d1a64f60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='chat-widget']</value>
      <webElementGuid>8ce605cc-14d9-451d-aebf-9f8deec1c4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chat-widget-container']/iframe</value>
      <webElementGuid>eb5f8d08-c8b7-4004-82ee-18a984035cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>78eea402-d3cb-4016-bd46-bf6003506c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://secure.livechatinc.com/customer/action/open_chat?license_id=14037057&amp;group=3&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0' and @id = 'chat-widget' and @name = 'chat-widget' and @title = 'LiveChat chat widget']</value>
      <webElementGuid>02c7ae3e-30fe-4ae1-844e-6542175c8fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
