<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MISA meInvoice_TaxCode</name>
   <tag></tag>
   <elementGuidId>c39db826-46d7-42a2-a192-798700b57438</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TaxCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TaxCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c7242da-0c66-4ff5-add1-bcfee0c3e801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mdc-text-field__input b-radius-4</value>
      <webElementGuid>d995d130-1f25-487b-8467-9649cb5d824e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TaxCode</value>
      <webElementGuid>e4860e53-4ab7-47f6-93fb-1d3804590c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TaxCode</value>
      <webElementGuid>2315a2af-330f-448b-ba86-5c312f45fb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4711c04c-ae44-467f-a592-71bc20796825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TaxCode&quot;)</value>
      <webElementGuid>2d4e66a6-0c60-46da-9465-b01634ef7964</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TaxCode']</value>
      <webElementGuid>148099ed-b0d7-4c0c-81b2-bd089476fe87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LoginForm']/div[4]/div/input</value>
      <webElementGuid>2b73b57b-d469-4cc5-9f4c-1be990ea400b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>09b00ed7-8160-4833-9220-9b26a037ca93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TaxCode' and @name = 'TaxCode' and @type = 'text']</value>
      <webElementGuid>3defb18d-2728-4320-ab0a-635a355b0565</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
